export const COUNTRIES_LIBRARY = [
    {
        "capital": "Berlin",
        "code": "de",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/de.svg",
        "flag_4x3": "flags/4x3/de.svg",
        "iso": true,
        "name": "Germany",
        "ISO_Code": "276",
        "german_name": "Deutschland ",
        "international_area_code": 49,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Warsaw",
        "code": "pl",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/pl.svg",
        "flag_4x3": "flags/4x3/pl.svg",
        "iso": true,
        "name": "Poland",
        "ISO_Code": "616",
        "german_name": "Polen ",
        "international_area_code": 48,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Ankara",
        "code": "tr",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/tr.svg",
        "flag_4x3": "flags/4x3/tr.svg",
        "iso": true,
        "name": "Türkiye",
        "ISO_Code": "792",
        "german_name": "Türkei",
        "international_area_code": 90,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Kabul",
        "code": "af",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/af.svg",
        "flag_4x3": "flags/4x3/af.svg",
        "iso": true,
        "name": "Afghanistan",
        "ISO_Code": "004",
        "german_name": "Afghanistan ",
        "international_area_code": 93,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Tirana",
        "code": "al",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/al.svg",
        "flag_4x3": "flags/4x3/al.svg",
        "iso": true,
        "name": "Albania",
        "ISO_Code": "008",
        "german_name": "Albanien ",
        "international_area_code": 355,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Algiers",
        "code": "dz",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/dz.svg",
        "flag_4x3": "flags/4x3/dz.svg",
        "iso": true,
        "name": "Algeria",
        "ISO_Code": "012",
        "german_name": "Algerien ",
        "international_area_code": 213,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Pago Pago",
        "code": "as",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/as.svg",
        "flag_4x3": "flags/4x3/as.svg",
        "iso": true,
        "name": "American Samoa",
        "ISO_Code": "016",
        "german_name": "Amerikanisch Samoa ",
        "international_area_code": 1684,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Charlotte Amalie",
        "code": "vi",
        "continent": "North America",
        "flag_1x1": "flags/1x1/vi.svg",
        "flag_4x3": "flags/4x3/vi.svg",
        "iso": true,
        "name": "Virgin Islands (U.S.)",
        "ISO_Code": "850",
        "german_name": "Amerikanische Jungferninseln",
        "international_area_code": 1340,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Andorra la Vella",
        "code": "ad",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/ad.svg",
        "flag_4x3": "flags/4x3/ad.svg",
        "iso": true,
        "name": "Andorra",
        "ISO_Code": "020",
        "german_name": "Andorra ",
        "international_area_code": 376,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Luanda",
        "code": "ao",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ao.svg",
        "flag_4x3": "flags/4x3/ao.svg",
        "iso": true,
        "name": "Angola",
        "ISO_Code": "024",
        "german_name": "Angola ",
        "international_area_code": 244,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "The Valley",
        "code": "ai",
        "continent": "North America",
        "flag_1x1": "flags/1x1/ai.svg",
        "flag_4x3": "flags/4x3/ai.svg",
        "iso": true,
        "name": "Anguilla",
        "ISO_Code": "660",
        "german_name": "Anguilla ",
        "international_area_code": 1264,
        "length_of_international_area_code_+_00": 6
    },
    {
        "code": "aq",
        "flag_1x1": "flags/1x1/aq.svg",
        "flag_4x3": "flags/4x3/aq.svg",
        "iso": true,
        "name": "Antarctica",
        "ISO_Code": "010",
        "german_name": "Antarktis ",
        "international_area_code": 672,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "St. John's",
        "code": "ag",
        "continent": "North America",
        "flag_1x1": "flags/1x1/ag.svg",
        "flag_4x3": "flags/4x3/ag.svg",
        "iso": true,
        "name": "Antigua and Barbuda",
        "ISO_Code": "028",
        "german_name": "Antigua and Barbuda ",
        "international_area_code": 1268,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Buenos Aires",
        "code": "ar",
        "continent": "South America",
        "flag_1x1": "flags/1x1/ar.svg",
        "flag_4x3": "flags/4x3/ar.svg",
        "iso": true,
        "name": "Argentina",
        "ISO_Code": "032",
        "german_name": "Argentinien ",
        "international_area_code": 54,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Yerevan",
        "code": "am",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/am.svg",
        "flag_4x3": "flags/4x3/am.svg",
        "iso": true,
        "name": "Armenia",
        "ISO_Code": "051",
        "german_name": "Armenien ",
        "international_area_code": 374,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Oranjestad",
        "code": "aw",
        "continent": "South America",
        "flag_1x1": "flags/1x1/aw.svg",
        "flag_4x3": "flags/4x3/aw.svg",
        "iso": true,
        "name": "Aruba",
        "ISO_Code": "533",
        "german_name": "Aruba ",
        "international_area_code": 297,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Baku",
        "code": "az",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/az.svg",
        "flag_4x3": "flags/4x3/az.svg",
        "iso": true,
        "name": "Azerbaijan",
        "ISO_Code": "031",
        "german_name": "Aserbaidschan ",
        "international_area_code": 994,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Canberra",
        "code": "au",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/au.svg",
        "flag_4x3": "flags/4x3/au.svg",
        "iso": true,
        "name": "Australia",
        "ISO_Code": "036",
        "german_name": "Australien ",
        "international_area_code": 61,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Nassau",
        "code": "bs",
        "continent": "North America",
        "flag_1x1": "flags/1x1/bs.svg",
        "flag_4x3": "flags/4x3/bs.svg",
        "iso": true,
        "name": "Bahamas",
        "ISO_Code": "044",
        "german_name": "Bahamas ",
        "international_area_code": 1242,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Manama",
        "code": "bh",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/bh.svg",
        "flag_4x3": "flags/4x3/bh.svg",
        "iso": true,
        "name": "Bahrain",
        "ISO_Code": "048",
        "german_name": "Bahrain ",
        "international_area_code": 973,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Dhaka",
        "code": "bd",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/bd.svg",
        "flag_4x3": "flags/4x3/bd.svg",
        "iso": true,
        "name": "Bangladesh",
        "ISO_Code": "050",
        "german_name": "Bangladesh ",
        "international_area_code": 880,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Bridgetown",
        "code": "bb",
        "continent": "North America",
        "flag_1x1": "flags/1x1/bb.svg",
        "flag_4x3": "flags/4x3/bb.svg",
        "iso": true,
        "name": "Barbados",
        "ISO_Code": "052",
        "german_name": "Barbados ",
        "international_area_code": 1246,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Minsk",
        "code": "by",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/by.svg",
        "flag_4x3": "flags/4x3/by.svg",
        "iso": true,
        "name": "Belarus",
        "ISO_Code": "112",
        "german_name": "Belarus (Weissrussland)",
        "international_area_code": 375,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Brussels",
        "code": "be",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/be.svg",
        "flag_4x3": "flags/4x3/be.svg",
        "iso": true,
        "name": "Belgium",
        "ISO_Code": "056",
        "german_name": "Belgien",
        "international_area_code": 32,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Belmopan",
        "code": "bz",
        "continent": "North America",
        "flag_1x1": "flags/1x1/bz.svg",
        "flag_4x3": "flags/4x3/bz.svg",
        "iso": true,
        "name": "Belize",
        "ISO_Code": "084",
        "german_name": "Belize ",
        "international_area_code": 501,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Porto-Novo",
        "code": "bj",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/bj.svg",
        "flag_4x3": "flags/4x3/bj.svg",
        "iso": true,
        "name": "Benin",
        "ISO_Code": "204",
        "german_name": "Benin ",
        "international_area_code": 229,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Hamilton",
        "code": "bm",
        "continent": "North America",
        "flag_1x1": "flags/1x1/bm.svg",
        "flag_4x3": "flags/4x3/bm.svg",
        "iso": true,
        "name": "Bermuda",
        "ISO_Code": "060",
        "german_name": "Bermuda ",
        "international_area_code": 1441,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Thimphu",
        "code": "bt",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/bt.svg",
        "flag_4x3": "flags/4x3/bt.svg",
        "iso": true,
        "name": "Bhutan",
        "ISO_Code": "068",
        "german_name": "Bhutan ",
        "international_area_code": 975,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Sucre",
        "code": "bo",
        "continent": "South America",
        "flag_1x1": "flags/1x1/bo.svg",
        "flag_4x3": "flags/4x3/bo.svg",
        "iso": true,
        "name": "Bolivia",
        "ISO_Code": "068",
        "german_name": "Bhutan ",
        "international_area_code": 591,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Sarajevo",
        "code": "ba",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/ba.svg",
        "flag_4x3": "flags/4x3/ba.svg",
        "iso": true,
        "name": "Bosnia and Herzegovina",
        "ISO_Code": "070",
        "german_name": "Bosnien und Herzegowina",
        "international_area_code": 387,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Gaborone",
        "code": "bw",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/bw.svg",
        "flag_4x3": "flags/4x3/bw.svg",
        "iso": true,
        "name": "Botswana",
        "ISO_Code": "072",
        "german_name": "Botswana ",
        "international_area_code": 267,
        "length_of_international_area_code_+_00": 5
    },
    {
        "code": "bv",
        "flag_1x1": "flags/1x1/bv.svg",
        "flag_4x3": "flags/4x3/bv.svg",
        "iso": true,
        "name": "Bouvet Island",
        "ISO_Code": "074",
        "german_name": "Bouvetinsel",
        "international_area_code": 47,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Brasília",
        "code": "br",
        "continent": "South America",
        "flag_1x1": "flags/1x1/br.svg",
        "flag_4x3": "flags/4x3/br.svg",
        "iso": true,
        "name": "Brazil",
        "ISO_Code": "076",
        "german_name": "Brasilien",
        "international_area_code": 5,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Road Town",
        "code": "vg",
        "continent": "North America",
        "flag_1x1": "flags/1x1/vg.svg",
        "flag_4x3": "flags/4x3/vg.svg",
        "iso": true,
        "name": "Virgin Islands (British)",
        "ISO_Code": "092",
        "german_name": "Britische Jungferninseln",
        "international_area_code": 1284,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Diego Garcia",
        "code": "io",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/io.svg",
        "flag_4x3": "flags/4x3/io.svg",
        "iso": true,
        "name": "British Indian Ocean Territory",
        "ISO_Code": "086",
        "german_name": "Britisches Territorium im Indischen Ozean",
        "international_area_code": 246,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Bandar Seri Begawan",
        "code": "bn",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/bn.svg",
        "flag_4x3": "flags/4x3/bn.svg",
        "iso": true,
        "name": "Brunei Darussalam",
        "ISO_Code": "096",
        "german_name": "Brunei",
        "international_area_code": 673,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Sofia",
        "code": "bg",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/bg.svg",
        "flag_4x3": "flags/4x3/bg.svg",
        "iso": true,
        "name": "Bulgaria",
        "ISO_Code": "100",
        "german_name": "Bulgarien",
        "international_area_code": 359,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Ouagadougou",
        "code": "bf",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/bf.svg",
        "flag_4x3": "flags/4x3/bf.svg",
        "iso": true,
        "name": "Burkina Faso",
        "ISO_Code": "854",
        "german_name": "Burkina Faso ",
        "international_area_code": 226,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Bujumbura",
        "code": "bi",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/bi.svg",
        "flag_4x3": "flags/4x3/bi.svg",
        "iso": true,
        "name": "Burundi",
        "ISO_Code": "108",
        "german_name": "Burundi ",
        "international_area_code": 257,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Santiago",
        "code": "cl",
        "continent": "South America",
        "flag_1x1": "flags/1x1/cl.svg",
        "flag_4x3": "flags/4x3/cl.svg",
        "iso": true,
        "name": "Chile",
        "ISO_Code": "152",
        "german_name": "Chile ",
        "international_area_code": 56,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Beijing",
        "code": "cn",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/cn.svg",
        "flag_4x3": "flags/4x3/cn.svg",
        "iso": true,
        "name": "China",
        "ISO_Code": "156",
        "german_name": "China ",
        "international_area_code": 86,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Avarua",
        "code": "ck",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/ck.svg",
        "flag_4x3": "flags/4x3/ck.svg",
        "iso": true,
        "name": "Cook Islands",
        "ISO_Code": "184",
        "german_name": "Cookinseln",
        "international_area_code": 682,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "San José",
        "code": "cr",
        "continent": "North America",
        "flag_1x1": "flags/1x1/cr.svg",
        "flag_4x3": "flags/4x3/cr.svg",
        "iso": true,
        "name": "Costa Rica",
        "ISO_Code": "188",
        "german_name": "Costa Rica ",
        "international_area_code": 506,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Yamoussoukro",
        "code": "ci",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ci.svg",
        "flag_4x3": "flags/4x3/ci.svg",
        "iso": true,
        "name": "Côte d'Ivoire",
        "ISO_Code": "384",
        "german_name": "Cote de Ivoire",
        "international_area_code": 225,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Roseau",
        "code": "dm",
        "continent": "North America",
        "flag_1x1": "flags/1x1/dm.svg",
        "flag_4x3": "flags/4x3/dm.svg",
        "iso": true,
        "name": "Dominica",
        "ISO_Code": "212",
        "german_name": "Dominica ",
        "international_area_code": 1767,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Santo Domingo",
        "code": "do",
        "continent": "North America",
        "flag_1x1": "flags/1x1/do.svg",
        "flag_4x3": "flags/4x3/do.svg",
        "iso": true,
        "name": "Dominican Republic",
        "ISO_Code": "214",
        "german_name": "Dominikanische Republik",
        "international_area_code": 1809,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Djibouti",
        "code": "dj",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/dj.svg",
        "flag_4x3": "flags/4x3/dj.svg",
        "iso": true,
        "name": "Djibouti",
        "ISO_Code": "262",
        "german_name": "Dschibuti",
        "international_area_code": 253,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Copenhagen",
        "code": "dk",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/dk.svg",
        "flag_4x3": "flags/4x3/dk.svg",
        "iso": true,
        "name": "Denmark",
        "ISO_Code": "208",
        "german_name": "Dänemark",
        "international_area_code": 45,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Quito",
        "code": "ec",
        "continent": "South America",
        "flag_1x1": "flags/1x1/ec.svg",
        "flag_4x3": "flags/4x3/ec.svg",
        "iso": true,
        "name": "Ecuador",
        "ISO_Code": "218",
        "german_name": "Ecuador ",
        "international_area_code": 593,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "San Salvador",
        "code": "sv",
        "continent": "North America",
        "flag_1x1": "flags/1x1/sv.svg",
        "flag_4x3": "flags/4x3/sv.svg",
        "iso": true,
        "name": "El Salvador",
        "ISO_Code": "222",
        "german_name": "El Salvador ",
        "international_area_code": 503,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Asmara",
        "code": "er",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/er.svg",
        "flag_4x3": "flags/4x3/er.svg",
        "iso": true,
        "name": "Eritrea",
        "ISO_Code": "232",
        "german_name": "Eritrea ",
        "international_area_code": 291,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Tallinn",
        "code": "ee",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/ee.svg",
        "flag_4x3": "flags/4x3/ee.svg",
        "iso": true,
        "name": "Estonia",
        "ISO_Code": "233",
        "german_name": "Estland ",
        "international_area_code": 372,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Stanley",
        "code": "fk",
        "continent": "South America",
        "flag_1x1": "flags/1x1/fk.svg",
        "flag_4x3": "flags/4x3/fk.svg",
        "iso": true,
        "name": "Falkland Islands",
        "ISO_Code": "238",
        "german_name": "Falklandinseln",
        "international_area_code": 500,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Suva",
        "code": "fj",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/fj.svg",
        "flag_4x3": "flags/4x3/fj.svg",
        "iso": true,
        "name": "Fiji",
        "ISO_Code": "242",
        "german_name": "Fidschi",
        "international_area_code": 679,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Helsinki",
        "code": "fi",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/fi.svg",
        "flag_4x3": "flags/4x3/fi.svg",
        "iso": true,
        "name": "Finland",
        "ISO_Code": "246",
        "german_name": "Finnland",
        "international_area_code": 358,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Paris",
        "code": "fr",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/fr.svg",
        "flag_4x3": "flags/4x3/fr.svg",
        "iso": true,
        "name": "France",
        "ISO_Code": "250",
        "german_name": "Frankreich",
        "international_area_code": 33,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Papeete",
        "code": "pf",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/pf.svg",
        "flag_4x3": "flags/4x3/pf.svg",
        "iso": true,
        "name": "French Polynesia",
        "ISO_Code": "258",
        "german_name": "Französisch-Polynesien",
        "international_area_code": 690,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Saint Pierre",
        "code": "tf",
        "continent": "Antarctica",
        "flag_1x1": "flags/1x1/pf.svg",
        "flag_4x3": "flags/4x3/pf.svg",
        "iso": true,
        "name": "French Southern and Antarctic Lands",
        "ISO_Code": "260",
        "german_name": "Französische Süd- und Antarktisgebiete",
        "international_area_code": 262,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Tórshavn",
        "code": "fo",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/fo.svg",
        "flag_4x3": "flags/4x3/fo.svg",
        "iso": true,
        "name": "Faroe Islands",
        "ISO_Code": "234",
        "german_name": "Färöer",
        "international_area_code": 298,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Libreville",
        "code": "ga",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ga.svg",
        "flag_4x3": "flags/4x3/ga.svg",
        "iso": true,
        "name": "Gabon",
        "ISO_Code": "266",
        "german_name": "Gabun",
        "international_area_code": 241,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Banjul",
        "code": "gm",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/gm.svg",
        "flag_4x3": "flags/4x3/gm.svg",
        "iso": true,
        "name": "Gambia",
        "ISO_Code": "270",
        "german_name": "Gambia",
        "international_area_code": 220,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Tbilisi",
        "code": "ge",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/ge.svg",
        "flag_4x3": "flags/4x3/ge.svg",
        "iso": true,
        "name": "Georgia",
        "ISO_Code": "268",
        "german_name": "Georgien",
        "international_area_code": 995,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Accra",
        "code": "gh",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/gh.svg",
        "flag_4x3": "flags/4x3/gh.svg",
        "iso": true,
        "name": "Ghana",
        "ISO_Code": "288",
        "german_name": "Ghana ",
        "international_area_code": 233,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Gibraltar",
        "code": "gi",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/gi.svg",
        "flag_4x3": "flags/4x3/gi.svg",
        "iso": true,
        "name": "Gibraltar",
        "ISO_Code": "292",
        "german_name": "Gibraltar ",
        "international_area_code": 350,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "St. George's",
        "code": "gd",
        "continent": "North America",
        "flag_1x1": "flags/1x1/gd.svg",
        "flag_4x3": "flags/4x3/gd.svg",
        "iso": true,
        "name": "Grenada",
        "ISO_Code": "308",
        "german_name": "Grenada ",
        "international_area_code": 1473,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Athens",
        "code": "gr",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/gr.svg",
        "flag_4x3": "flags/4x3/gr.svg",
        "iso": true,
        "name": "Greece",
        "ISO_Code": "300",
        "german_name": "Griechenland",
        "international_area_code": 30,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Nuuk",
        "code": "gl",
        "continent": "North America",
        "flag_1x1": "flags/1x1/gl.svg",
        "flag_4x3": "flags/4x3/gl.svg",
        "iso": true,
        "name": "Greenland",
        "ISO_Code": "304",
        "german_name": "Grönland",
        "international_area_code": 299,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Hagåtña",
        "code": "gu",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/gu.svg",
        "flag_4x3": "flags/4x3/gu.svg",
        "iso": true,
        "name": "Guam",
        "ISO_Code": "316",
        "german_name": "Guam ",
        "international_area_code": 1671,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Guatemala City",
        "code": "gt",
        "continent": "North America",
        "flag_1x1": "flags/1x1/gt.svg",
        "flag_4x3": "flags/4x3/gt.svg",
        "iso": true,
        "name": "Guatemala",
        "ISO_Code": "320",
        "german_name": "Guatemala ",
        "international_area_code": 502,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Saint Peter Port",
        "code": "gg",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/gg.svg",
        "flag_4x3": "flags/4x3/gg.svg",
        "iso": true,
        "name": "Guernsey",
        "ISO_Code": "831",
        "german_name": "Guernsey ",
        "international_area_code": 441481,
        "length_of_international_area_code_+_00": 8
    },
    {
        "capital": "Conakry",
        "code": "gn",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/gn.svg",
        "flag_4x3": "flags/4x3/gn.svg",
        "iso": true,
        "name": "Guinea",
        "ISO_Code": "324",
        "german_name": "Guinea ",
        "international_area_code": 224,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Bissau",
        "code": "gw",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/gw.svg",
        "flag_4x3": "flags/4x3/gw.svg",
        "iso": true,
        "name": "Guinea-Bissau",
        "ISO_Code": "624",
        "german_name": "Guinea-Bissau ",
        "international_area_code": 245,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Georgetown",
        "code": "gy",
        "continent": "South America",
        "flag_1x1": "flags/1x1/gy.svg",
        "flag_4x3": "flags/4x3/gy.svg",
        "iso": true,
        "name": "Guyana",
        "ISO_Code": "328",
        "german_name": "Guyana ",
        "international_area_code": 592,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Port-au-Prince",
        "code": "ht",
        "continent": "North America",
        "flag_1x1": "flags/1x1/ht.svg",
        "flag_4x3": "flags/4x3/ht.svg",
        "iso": true,
        "name": "Haiti",
        "ISO_Code": "332",
        "german_name": "Haiti ",
        "international_area_code": 509,
        "length_of_international_area_code_+_00": 5
    },
    {
        "code": "hm",
        "flag_1x1": "flags/1x1/hm.svg",
        "flag_4x3": "flags/4x3/hm.svg",
        "iso": true,
        "name": "Heard Island and McDonald Islands",
        "ISO_Code": "334",
        "german_name": "Heard and McDonald Inseln",
        "international_area_code": 672,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Tegucigalpa",
        "code": "hn",
        "continent": "North America",
        "flag_1x1": "flags/1x1/hn.svg",
        "flag_4x3": "flags/4x3/hn.svg",
        "iso": true,
        "name": "Honduras",
        "ISO_Code": "340",
        "german_name": "Honduras ",
        "international_area_code": 504,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "New Delhi",
        "code": "in",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/in.svg",
        "flag_4x3": "flags/4x3/in.svg",
        "iso": true,
        "name": "India",
        "ISO_Code": "356",
        "german_name": "Indien ",
        "international_area_code": 91,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Jakarta",
        "code": "id",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/id.svg",
        "flag_4x3": "flags/4x3/id.svg",
        "iso": true,
        "name": "Indonesia",
        "ISO_Code": "360",
        "german_name": "Indonesien",
        "international_area_code": 62,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Douglas",
        "code": "im",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/im.svg",
        "flag_4x3": "flags/4x3/im.svg",
        "iso": true,
        "name": "Isle of Man",
        "ISO_Code": "833",
        "german_name": "Insel Man",
        "international_area_code": 441624,
        "length_of_international_area_code_+_00": 8
    },
    {
        "capital": "Baghdad",
        "code": "iq",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/iq.svg",
        "flag_4x3": "flags/4x3/iq.svg",
        "iso": true,
        "name": "Iraq",
        "ISO_Code": "368",
        "german_name": "Irak",
        "international_area_code": 964,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Tehran",
        "code": "ir",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/ir.svg",
        "flag_4x3": "flags/4x3/ir.svg",
        "iso": true,
        "name": "Iran",
        "ISO_Code": "364",
        "german_name": "Iran ",
        "international_area_code": 98,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Dublin",
        "code": "ie",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/ie.svg",
        "flag_4x3": "flags/4x3/ie.svg",
        "iso": true,
        "name": "Ireland",
        "ISO_Code": "372",
        "german_name": "Irland",
        "international_area_code": 353,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Reykjavik",
        "code": "is",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/is.svg",
        "flag_4x3": "flags/4x3/is.svg",
        "iso": true,
        "name": "Iceland",
        "ISO_Code": "352",
        "german_name": "Island",
        "international_area_code": 354,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Jerusalem",
        "code": "il",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/il.svg",
        "flag_4x3": "flags/4x3/il.svg",
        "iso": true,
        "name": "Israel",
        "ISO_Code": "376",
        "german_name": "Israel ",
        "international_area_code": 972,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Rome",
        "code": "it",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/it.svg",
        "flag_4x3": "flags/4x3/it.svg",
        "iso": true,
        "name": "Italy",
        "ISO_Code": "380",
        "german_name": "Italien",
        "international_area_code": 39,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Kingston",
        "code": "jm",
        "continent": "North America",
        "flag_1x1": "flags/1x1/jm.svg",
        "flag_4x3": "flags/4x3/jm.svg",
        "iso": true,
        "name": "Jamaica",
        "ISO_Code": "388",
        "german_name": "Jamaika",
        "international_area_code": 1876,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Tokyo",
        "code": "jp",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/jp.svg",
        "flag_4x3": "flags/4x3/jp.svg",
        "iso": true,
        "name": "Japan",
        "ISO_Code": "392",
        "german_name": "Japan ",
        "international_area_code": 81,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Sana'a",
        "code": "ye",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/ye.svg",
        "flag_4x3": "flags/4x3/ye.svg",
        "iso": true,
        "name": "Yemen",
        "ISO_Code": "887",
        "german_name": "Jemen",
        "international_area_code": 967,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Saint Helier",
        "code": "je",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/je.svg",
        "flag_4x3": "flags/4x3/je.svg",
        "iso": true,
        "name": "Jersey",
        "ISO_Code": "832",
        "german_name": "Jersey ",
        "international_area_code": 441534,
        "length_of_international_area_code_+_00": 8
    },
    {
        "capital": "Amman",
        "code": "jo",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/jo.svg",
        "flag_4x3": "flags/4x3/jo.svg",
        "iso": true,
        "name": "Jordan",
        "ISO_Code": "400",
        "german_name": "Jordanien",
        "international_area_code": 962,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "South Tarawa",
        "code": "ki",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/ki.svg",
        "flag_4x3": "flags/4x3/ki.svg",
        "iso": true,
        "name": "Kiribati",
        "ISO_Code": "296",
        "german_name": "Kiribati ",
        "international_area_code": 686,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Pristina",
        "code": "xk",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/xk.svg",
        "flag_4x3": "flags/4x3/xk.svg",
        "iso": false,
        "name": "Kosovo",
        "ISO_Code": "900",
        "german_name": "Kosovo ",
        "international_area_code": 383,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Kuwait City",
        "code": "kw",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/kw.svg",
        "flag_4x3": "flags/4x3/kw.svg",
        "iso": true,
        "name": "Kuwait",
        "ISO_Code": "414",
        "german_name": "Kuwait ",
        "international_area_code": 965,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Vientiane",
        "code": "la",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/la.svg",
        "flag_4x3": "flags/4x3/la.svg",
        "iso": true,
        "name": "Laos",
        "ISO_Code": "418",
        "german_name": "Laos ",
        "international_area_code": 856,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Maseru",
        "code": "ls",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ls.svg",
        "flag_4x3": "flags/4x3/ls.svg",
        "iso": true,
        "name": "Lesotho",
        "ISO_Code": "426",
        "german_name": "Lesotho ",
        "international_area_code": 266,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Monrovia",
        "code": "lr",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/lr.svg",
        "flag_4x3": "flags/4x3/lr.svg",
        "iso": true,
        "name": "Liberia",
        "ISO_Code": "430",
        "german_name": "Liberia ",
        "international_area_code": 231,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Vaduz",
        "code": "li",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/li.svg",
        "flag_4x3": "flags/4x3/li.svg",
        "iso": true,
        "name": "Liechtenstein",
        "ISO_Code": "438",
        "german_name": "Liechtenstein ",
        "international_area_code": 423,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Macau",
        "code": "mo",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/mo.svg",
        "flag_4x3": "flags/4x3/mo.svg",
        "iso": true,
        "name": "Macau",
        "ISO_Code": "446",
        "german_name": "Macau ",
        "international_area_code": 853,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Lilongwe",
        "code": "mw",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/mw.svg",
        "flag_4x3": "flags/4x3/mw.svg",
        "iso": true,
        "name": "Malawi",
        "ISO_Code": "454",
        "german_name": "Malawi ",
        "international_area_code": 265,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Kuala Lumpur",
        "code": "my",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/my.svg",
        "flag_4x3": "flags/4x3/my.svg",
        "iso": true,
        "name": "Malaysia",
        "ISO_Code": "458",
        "german_name": "Malaysia ",
        "international_area_code": 60,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Bamako",
        "code": "ml",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ml.svg",
        "flag_4x3": "flags/4x3/ml.svg",
        "iso": true,
        "name": "Mali",
        "ISO_Code": "466",
        "german_name": "Mali ",
        "international_area_code": 223,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Valletta",
        "code": "mt",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/mt.svg",
        "flag_4x3": "flags/4x3/mt.svg",
        "iso": true,
        "name": "Malta",
        "ISO_Code": "470",
        "german_name": "Malta ",
        "international_area_code": 356,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Fort-de-France",
        "code": "mq",
        "continent": "North America",
        "flag_1x1": "flags/1x1/mq.svg",
        "flag_4x3": "flags/4x3/mq.svg",
        "iso": true,
        "name": "Martinique",
        "ISO_Code": "474",
        "german_name": "Martinique ",
        "international_area_code": 596,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Port Louis",
        "code": "mu",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/mu.svg",
        "flag_4x3": "flags/4x3/mu.svg",
        "iso": true,
        "name": "Mauritius",
        "ISO_Code": "480",
        "german_name": "Mauritius ",
        "international_area_code": 230,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Mamoudzou",
        "code": "yt",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/yt.svg",
        "flag_4x3": "flags/4x3/yt.svg",
        "iso": true,
        "name": "Mayotte",
        "ISO_Code": "175",
        "german_name": "Mayotte ",
        "international_area_code": 262,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Podgorica",
        "code": "me",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/me.svg",
        "flag_4x3": "flags/4x3/me.svg",
        "iso": true,
        "name": "Montenegro",
        "ISO_Code": "499",
        "german_name": "Montenegro ",
        "international_area_code": 382,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Little Bay, Brades, Plymouth",
        "code": "ms",
        "continent": "North America",
        "flag_1x1": "flags/1x1/ms.svg",
        "flag_4x3": "flags/4x3/ms.svg",
        "iso": true,
        "name": "Montserrat",
        "ISO_Code": "500",
        "german_name": "Montserrat ",
        "international_area_code": 1664,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Naypyidaw",
        "code": "mm",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/mm.svg",
        "flag_4x3": "flags/4x3/mm.svg",
        "iso": true,
        "name": "Myanmar",
        "ISO_Code": "104",
        "german_name": "Myanmar ",
        "international_area_code": 95,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Windhoek",
        "code": "na",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/na.svg",
        "flag_4x3": "flags/4x3/na.svg",
        "iso": true,
        "name": "Namibia",
        "ISO_Code": "516",
        "german_name": "Namibia ",
        "international_area_code": 264,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Yaren District",
        "code": "nr",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/nr.svg",
        "flag_4x3": "flags/4x3/nr.svg",
        "iso": true,
        "name": "Nauru",
        "ISO_Code": "520",
        "german_name": "Nauru ",
        "international_area_code": 674,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Kathmandu",
        "code": "np",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/np.svg",
        "flag_4x3": "flags/4x3/np.svg",
        "iso": true,
        "name": "Nepal",
        "ISO_Code": "524",
        "german_name": "Nepal ",
        "international_area_code": 977,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Managua",
        "code": "ni",
        "continent": "North America",
        "flag_1x1": "flags/1x1/ni.svg",
        "flag_4x3": "flags/4x3/ni.svg",
        "iso": true,
        "name": "Nicaragua",
        "ISO_Code": "558",
        "german_name": "Nicaragua ",
        "international_area_code": 505,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Niamey",
        "code": "ne",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ne.svg",
        "flag_4x3": "flags/4x3/ne.svg",
        "iso": true,
        "name": "Niger",
        "ISO_Code": "562",
        "german_name": "Niger ",
        "international_area_code": 227,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Abuja",
        "code": "ng",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ng.svg",
        "flag_4x3": "flags/4x3/ng.svg",
        "iso": true,
        "name": "Nigeria",
        "ISO_Code": "566",
        "german_name": "Nigeria ",
        "international_area_code": 234,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Alofi",
        "code": "nu",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/nu.svg",
        "flag_4x3": "flags/4x3/nu.svg",
        "iso": true,
        "name": "Niue",
        "ISO_Code": "570",
        "german_name": "Niue ",
        "international_area_code": 683,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Muscat",
        "code": "om",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/om.svg",
        "flag_4x3": "flags/4x3/om.svg",
        "iso": true,
        "name": "Oman",
        "ISO_Code": "512",
        "german_name": "Oman ",
        "international_area_code": 968,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Islamabad",
        "code": "pk",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/pk.svg",
        "flag_4x3": "flags/4x3/pk.svg",
        "iso": true,
        "name": "Pakistan",
        "ISO_Code": "586",
        "german_name": "Pakistan ",
        "international_area_code": 92,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Ngerulmud",
        "code": "pw",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/pw.svg",
        "flag_4x3": "flags/4x3/pw.svg",
        "iso": true,
        "name": "Palau",
        "ISO_Code": "585",
        "german_name": "Palau ",
        "international_area_code": 680,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Panama City",
        "code": "pa",
        "continent": "North America",
        "flag_1x1": "flags/1x1/pa.svg",
        "flag_4x3": "flags/4x3/pa.svg",
        "iso": true,
        "name": "Panama",
        "ISO_Code": "591",
        "german_name": "Panama ",
        "international_area_code": 507,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Asunción",
        "code": "py",
        "continent": "South America",
        "flag_1x1": "flags/1x1/py.svg",
        "flag_4x3": "flags/4x3/py.svg",
        "iso": true,
        "name": "Paraguay",
        "ISO_Code": "600",
        "german_name": "Paraguay ",
        "international_area_code": 595,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Lima",
        "code": "pe",
        "continent": "South America",
        "flag_1x1": "flags/1x1/pe.svg",
        "flag_4x3": "flags/4x3/pe.svg",
        "iso": true,
        "name": "Peru",
        "ISO_Code": "604",
        "german_name": "Peru ",
        "international_area_code": 51,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Lisbon",
        "code": "pt",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/pt.svg",
        "flag_4x3": "flags/4x3/pt.svg",
        "iso": true,
        "name": "Portugal",
        "ISO_Code": "620",
        "german_name": "Portugal ",
        "international_area_code": 351,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "San Juan",
        "code": "pr",
        "continent": "North America",
        "flag_1x1": "flags/1x1/pr.svg",
        "flag_4x3": "flags/4x3/pr.svg",
        "iso": true,
        "name": "Puerto Rico",
        "ISO_Code": "630",
        "german_name": "Puerto Rico ",
        "international_area_code": 1787,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Apia",
        "code": "ws",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/ws.svg",
        "flag_4x3": "flags/4x3/ws.svg",
        "iso": true,
        "name": "Samoa",
        "ISO_Code": "882",
        "german_name": "Samoa ",
        "international_area_code": 685,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "San Marino",
        "code": "sm",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/sm.svg",
        "flag_4x3": "flags/4x3/sm.svg",
        "iso": true,
        "name": "San Marino",
        "ISO_Code": "674",
        "german_name": "San Marino ",
        "international_area_code": 378,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Dakar",
        "code": "sn",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/sn.svg",
        "flag_4x3": "flags/4x3/sn.svg",
        "iso": true,
        "name": "Senegal",
        "ISO_Code": "686",
        "german_name": "Senegal ",
        "international_area_code": 221,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Freetown",
        "code": "sl",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/sl.svg",
        "flag_4x3": "flags/4x3/sl.svg",
        "iso": true,
        "name": "Sierra Leone",
        "ISO_Code": "694",
        "german_name": "Sierra Leone ",
        "international_area_code": 232,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Mogadishu",
        "code": "so",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/so.svg",
        "flag_4x3": "flags/4x3/so.svg",
        "iso": true,
        "name": "Somalia",
        "ISO_Code": "706",
        "german_name": "Somalia ",
        "international_area_code": 252,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Sri Jayawardenepura Kotte, Colombo",
        "code": "lk",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/lk.svg",
        "flag_4x3": "flags/4x3/lk.svg",
        "iso": true,
        "name": "Sri Lanka",
        "ISO_Code": "144",
        "german_name": "Sri Lanka ",
        "international_area_code": 94,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Khartoum",
        "code": "sd",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/sd.svg",
        "flag_4x3": "flags/4x3/sd.svg",
        "iso": true,
        "name": "Sudan",
        "ISO_Code": "729",
        "german_name": "Sudan ",
        "international_area_code": 249,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Paramaribo",
        "code": "sr",
        "continent": "South America",
        "flag_1x1": "flags/1x1/sr.svg",
        "flag_4x3": "flags/4x3/sr.svg",
        "iso": true,
        "name": "Suriname",
        "ISO_Code": "740",
        "german_name": "Suriname ",
        "international_area_code": 597,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Taipei",
        "code": "tw",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/tw.svg",
        "flag_4x3": "flags/4x3/tw.svg",
        "iso": true,
        "name": "Taiwan",
        "ISO_Code": "158",
        "german_name": "Taiwan ",
        "international_area_code": 886,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Bangkok",
        "code": "th",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/th.svg",
        "flag_4x3": "flags/4x3/th.svg",
        "iso": true,
        "name": "Thailand",
        "ISO_Code": "764",
        "german_name": "Thailand ",
        "international_area_code": 66,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Lomé",
        "code": "tg",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/tg.svg",
        "flag_4x3": "flags/4x3/tg.svg",
        "iso": true,
        "name": "Togo",
        "ISO_Code": "768",
        "german_name": "Togo ",
        "international_area_code": 228,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Nukunonu, Atafu,Tokelau",
        "code": "tk",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/tk.svg",
        "flag_4x3": "flags/4x3/tk.svg",
        "iso": true,
        "name": "Tokelau",
        "ISO_Code": "772",
        "german_name": "Tokelau ",
        "international_area_code": 690,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Nukuʻalofa",
        "code": "to",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/to.svg",
        "flag_4x3": "flags/4x3/to.svg",
        "iso": true,
        "name": "Tonga",
        "ISO_Code": "776",
        "german_name": "Tonga ",
        "international_area_code": 676,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Port of Spain",
        "code": "tt",
        "continent": "South America",
        "flag_1x1": "flags/1x1/tt.svg",
        "flag_4x3": "flags/4x3/tt.svg",
        "iso": true,
        "name": "Trinidad and Tobago",
        "ISO_Code": "780",
        "german_name": "Trinidad and Tobago ",
        "international_area_code": 1868,
        "length_of_international_area_code_+_00": 6
    },
    {
        "capital": "Ashgabat",
        "code": "tm",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/tm.svg",
        "flag_4x3": "flags/4x3/tm.svg",
        "iso": true,
        "name": "Turkmenistan",
        "ISO_Code": "795",
        "german_name": "Turkmenistan ",
        "international_area_code": 993,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Funafuti",
        "code": "tv",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/tv.svg",
        "flag_4x3": "flags/4x3/tv.svg",
        "iso": true,
        "name": "Tuvalu",
        "ISO_Code": "798",
        "german_name": "Tuvalu ",
        "international_area_code": 688,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Kampala",
        "code": "ug",
        "continent": "Africa",
        "flag_1x1": "flags/1x1/ug.svg",
        "flag_4x3": "flags/4x3/ug.svg",
        "iso": true,
        "name": "Uganda",
        "ISO_Code": "800",
        "german_name": "Uganda ",
        "international_area_code": 256,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Kiev",
        "code": "ua",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/ua.svg",
        "flag_4x3": "flags/4x3/ua.svg",
        "iso": true,
        "name": "Ukraine",
        "ISO_Code": "804",
        "german_name": "Ukraine ",
        "international_area_code": 380,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Montevideo",
        "code": "uy",
        "continent": "South America",
        "flag_1x1": "flags/1x1/uy.svg",
        "flag_4x3": "flags/4x3/uy.svg",
        "iso": true,
        "name": "Uruguay",
        "ISO_Code": "858",
        "german_name": "Uruguay ",
        "international_area_code": 598,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Port Vila",
        "code": "vu",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/vu.svg",
        "flag_4x3": "flags/4x3/vu.svg",
        "iso": true,
        "name": "Vanuatu",
        "ISO_Code": "548",
        "german_name": "Vanuatu ",
        "international_area_code": 678,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Caracas",
        "code": "ve",
        "continent": "South America",
        "flag_1x1": "flags/1x1/ve.svg",
        "flag_4x3": "flags/4x3/ve.svg",
        "iso": true,
        "name": "Venezuela",
        "ISO_Code": "862",
        "german_name": "Venezuela ",
        "international_area_code": 58,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Hanoi",
        "code": "vn",
        "continent": "Asia",
        "flag_1x1": "flags/1x1/vn.svg",
        "flag_4x3": "flags/4x3/vn.svg",
        "iso": true,
        "name": "Vietnam",
        "ISO_Code": "704",
        "german_name": "Vietnam ",
        "international_area_code": 84,
        "length_of_international_area_code_+_00": 4
    },
    {
        "capital": "Mata-Utu",
        "code": "wf",
        "continent": "Oceania",
        "flag_1x1": "flags/1x1/wf.svg",
        "flag_4x3": "flags/4x3/wf.svg",
        "iso": true,
        "name": "Wallis and Futuna",
        "ISO_Code": "876",
        "german_name": "Wallis and Futuna ",
        "international_area_code": 681,
        "length_of_international_area_code_+_00": 5
    },
    {
        "capital": "Vienna",
        "code": "at",
        "continent": "Europe",
        "flag_1x1": "flags/1x1/at.svg",
        "flag_4x3": "flags/4x3/at.svg",
        "iso": true,
        "name": "Austria",
        "ISO_Code": "040",
        "german_name": "Österreich ",
        "international_area_code": 43,
        "length_of_international_area_code_+_00": 4
    }
]