export enum CWPFlowStepsSequence {
  personalData_salutationAndNamePage = 1,
  personalData_emailPage = 2,
  personalData_birthDatePage = 3,
  personalData_maritalStatusPage = 4,
  contactDetails_addressCurrentPage = 5,
  contactDetails_addressPreviousPage = 6,
  contactDetails_phoneNumberPage = 7,
  nationality_nationalityPage = 8,
  bankDetails_bankDetailsPage = 9,
  employmentDetails_employmentRelationtshipPage = 10,
  employmentDetails_timeWorkingForCurrentEmployerPage = 11,
  employmentDetails_industryTypeAndMajoritySalesCountryPage = 12,
  employmentDetails_employerAddressPage = 13,
  regularExpenses_whoDoYouLiveWithPage = 14,
  regularExpenses_haveChildrenWhomYouAreResponsiblePage = 15,
  overallOverview_summaryPage = 16,
}
