export default  {
    "months": [
        {
            "id":1,
            "name":"Januar",
            "acronym":"Jan",
            "value":0
        },{
            "id":2,
            "name":"Februar",
            "acronym":"Feb",
            "value":1
        },{
            "id":3,
            "name":"März",
            "acronym":"Mär",
            "value":2
        },{
            "id":4,
            "name":"April",
            "acronym":"Apr",
            "value":3
        },{
            "id":5,
            "name":"Mai",
            "acronym":"Mai",
            "value":4
        },{
            "id":6,
            "name":"Juni",
            "acronym":"Jun",
            "value":5
        },{
            "id":7,
            "name":"Juli",
            "acronym":"Jul",
            "value":6
        },{
            "id":8,
            "name":"August",
            "acronym":"Aug",
            "value":7
        },{
            "id":9,
            "name":"September",
            "acronym":"Sep",
            "value":8
        },{
            "id":10,
            "name":"Oktober",
            "acronym":"Okt",
            "value":9
        },{
            "id":11,
            "name":"November",
            "acronym":"Nov",
            "value":10
        },{
            "id":12,
            "name":"Dezember",
            "acronym":"Dez",
            "value":11
        }
    ]
}